[package]
name = "zl"
version = "0.1.0"
edition = "2024"

[dependencies]
zl-macros = { path = "macros" }
zl-sys = { path = "sys" }

[build-dependencies]
cc = "1.2.16"

[dev-dependencies]
pollster = "0.4.0"

[workspace]
members = [
    "macros",
    "sys"
]
