[package]
name = "zl"
version = "0.1.0"
edition = "2024"

[dependencies]
zl-macros = { path = "macros" }
zl-sys = { path = "zl-sys" }

[build-dependencies]
cc = "1.2.16"

[workspace]
members = [
    "macros",
    "zl-sys"
]
