[package]
name = "zl"
version = "0.1.0"
edition = "2024"

[dependencies]
cpplink = { path = "cpplink" }
zl-macros = { path = "macros" }
zl-sys = { path = "sys" }

[build-dependencies]
cc = "1.2.16"

[workspace]
members = [
    "cpplink",
    "macros",
    "sys"
]
