[package]
name = "zl-sys"
version = "0.1.0"
edition = "2024"
links = "lua"

[dependencies]

[build-dependencies]
cc = "1.2.16"
flate2 = "1.1.0"
tar = { version = "0.4.44", default-features = false }
ureq = { version = "3.0.9", features = ["platform-verifier"] }
